name: Release
permissions:
  contents: read
on:
  push:
    branches:
      - main
      - beta

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for trusted publishing and npm provenance
    steps:
      - name: Checkout ✅
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup pnpm 🛠️
        uses: pnpm/action-setup@v6

      - name: Setup Node.js 🛠️
        uses: actions/setup-node@v6
        with:
          node-version: "lts/*"

      - name: Install dependencies 🔧
        run: pnpm install --ignore-scripts

      - name: Release 🚀
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release
