name: Unit tests
permissions:
  contents: read
  statuses: write
on:
  pull_request:
  push:
    branches:
      - main
      - beta

jobs:
  lint:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ✅
        uses: actions/checkout@v6

      - name: Setup pnpm 🛠️
        uses: pnpm/action-setup@v5

      - name: Setup Node.js 🛠️
        uses: actions/setup-node@v6
        with:
          node-version: "lts/*"
          cache: "pnpm"

      - name: Install dependencies 🔧
        run: pnpm i

      - name: Run Vitest (with coverage report) 🧪
        run: pnpm run test:unit

      - name: Codecov 📝
        uses: codecov/codecov-action@v5
        with:
          directory: ./tests/unit/coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
